
UPDATE "history" SET "Plattform"='Playstation 4' WHERE "Plattform"='PS4';

SELECT * FROM history WHERE "View" like '2D%' LIMIT 100

ALTER TABLE perspectives
ADD PRIMARY KEY(perspective_id);

ALTER TABLE platforms
ADD CONSTRAINT unique_platform_name UNIQUE (platform_name);

CREATE TABLE categorie_tags(
    tag_id INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    tag_name VARCHAR(50) UNIQUE,
    PRIMARY KEY(tag_id)
)

CREATE TABLE product_tags (
    product_id INTEGER REFERENCES products(id),
    tag_id INTEGER REFERENCES tags(id),
    PRIMARY KEY (product_id, tag_id)
);

CREATE TABLE game_category_tags(
    tag_id INTEGER REFERENCES category_tags(tag_id),
    game_id INTEGER REFERENCES games(game_id),
    PRIMARY KEY(tag_id, game_id)
);

-- Generated by the database client.
CREATE TABLE history(
    game_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    name text NOT NULL,
    "Kategorie" text,
    platform text,
    finished_at text,
    playtime text,
    view_perspective text,
    category_id integer,
    perspective_id integer,
    platform_id integer,
    PRIMARY KEY(game_id)
);
CREATE INDEX ix_history_index ON public.history USING btree (game_id);


ALTER TABLE history
ADD COLUMN platform_id INTEGER;


ALTER TABLE history
DROP COLUMN "view_dimensions";


UPDATE "history" SET "viewtype"='3rd person' WHERE "View" like '%%';

UPDATE "history" SET "view_dimensions"= 2 WHERE "View" like '2D%';
UPDATE "history" SET "viewtype"='isometric' WHERE "View" like '%iso%';
UPDATE "history" SET "viewtype"='isometric' WHERE "View" like '%iso%';

INSERT INTO platforms (platform_name)
VALUES  
    ('Playstation 3'),
    ('Playstation 4'),
    ('Playstation 5'),
    ('PS Vita'),
    ('Xbox One'),
    ('PC Windows'),
    ('Switch'),
    ('Wii U'),
    ('Mac');

SELECT DISTINCT view_perspective FROM games;


INSERT INTO perspectives (perspective_name)
VALUES
('2.5D sidescroller'),
('1st person'),
('isometric'),
('2D sidescroller'),
('2D static'),
('3rd person'),
('top down');

SELECT DISTINCT "Kategorie" FROM games;

INSERT INTO category_tags (tag_name) VALUES
('JRPG'),
('Taktik-RPG'),
('Metroidvania'),
('Puzzle platformer'),
('Puzzle adventure'),
('RTS'),
('Puzzle'),
('Detektiv adventure'),
('Beat em Up'),
('Action-RPG'),
('2D-platformer'),
('RPG'),
('Survival'),
('Crafting'),
('Action'),
('3D-platformer'),
('Point-and-click adventure'),
('Narrative adventure'),
('Deckbuilding'),
('Interactive film');

UPDATE games SET finished=True;

UPDATE games 
SET playtime = CAST(playtime_h AS NUMERIC);

UPDATE games
SET playtime_h = rawdata."Spielzeit / h"
FROM rawdata
WHERE games.game_id = rawdata."index";
